// Package oapicodegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package oapicodegen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for ErrorResponseResponseCode.
const (
	BADGATEWAY                    ErrorResponseResponseCode = "BAD_GATEWAY"
	BADREQUEST                    ErrorResponseResponseCode = "BAD_REQUEST"
	CONFLICT                      ErrorResponseResponseCode = "CONFLICT"
	EXPECTATIONFAILED             ErrorResponseResponseCode = "EXPECTATION_FAILED"
	GATEWAYTIMEOUT                ErrorResponseResponseCode = "GATEWAY_TIMEOUT"
	GONE                          ErrorResponseResponseCode = "GONE"
	HTTPVERSIONNOTSUPPORTED       ErrorResponseResponseCode = "HTTP_VERSION_NOT_SUPPORTED"
	INTERNALSERVERERROR           ErrorResponseResponseCode = "INTERNAL_SERVER_ERROR"
	LENGTHREQUIRED                ErrorResponseResponseCode = "LENGTH_REQUIRED"
	METHODNOTALLOWED              ErrorResponseResponseCode = "METHOD_NOT_ALLOWED"
	NETWORKAUTHENTICATIONREQUIRED ErrorResponseResponseCode = "NETWORK_AUTHENTICATION_REQUIRED"
	NOTACCEPTABLE                 ErrorResponseResponseCode = "NOT_ACCEPTABLE"
	NOTIMPLEMENTED                ErrorResponseResponseCode = "NOT_IMPLEMENTED"
	PRECONDITIONFAILED            ErrorResponseResponseCode = "PRECONDITION_FAILED"
	PRECONDITIONREQUIRED          ErrorResponseResponseCode = "PRECONDITION_REQUIRED"
	REQUESTEDRANGENOTSATISFIABLE  ErrorResponseResponseCode = "REQUESTED_RANGE_NOT_SATISFIABLE"
	REQUESTENTITYTOOLARGE         ErrorResponseResponseCode = "REQUEST_ENTITY_TOO_LARGE"
	REQUESTHEADERFIELDSTOOLARGE   ErrorResponseResponseCode = "REQUEST_HEADER_FIELDS_TOO_LARGE"
	REQUESTTIMEOUT                ErrorResponseResponseCode = "REQUEST_TIMEOUT"
	REQUESTURITOOLONG             ErrorResponseResponseCode = "REQUEST_URI_TOO_LONG"
	SERVICEUNAVAILABLE            ErrorResponseResponseCode = "SERVICE_UNAVAILABLE"
	TOOMANYREQUESTS               ErrorResponseResponseCode = "TOO_MANY_REQUESTS"
	UNAUTHORIZED                  ErrorResponseResponseCode = "UNAUTHORIZED"
	UNSUPPORTEDMEDIATYPE          ErrorResponseResponseCode = "UNSUPPORTED_MEDIA_TYPE"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorDetails *[]string                  `json:"errorDetails,omitempty"`
	ErrorMessage *string                    `json:"errorMessage,omitempty"`
	PolicyName   *string                    `json:"policyName,omitempty"`
	ResponseCode *ErrorResponseResponseCode `json:"responseCode,omitempty"`
}

// ErrorResponseResponseCode defines model for ErrorResponse.ResponseCode.
type ErrorResponseResponseCode string

// HealthCheckReport defines model for HealthCheckReport.
type HealthCheckReport struct {
	Code    *int32  `json:"code,omitempty"`
	Healthy *bool   `json:"healthy,omitempty"`
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
	Url     *string `json:"url,omitempty"`
}

// OPADecisionRequest defines model for OPADecisionRequest.
type OPADecisionRequest struct {
	CurrentDate     *openapi_types.Date     `json:"currentDate,omitempty"`
	CurrentDateTime *time.Time              `json:"currentDateTime,omitempty"`
	CurrentTime     *time.Time              `json:"currentTime,omitempty"`
	Input           *map[string]interface{} `json:"input,omitempty"`
	OnapComponent   *string                 `json:"onapComponent,omitempty"`
	OnapInstance    *string                 `json:"onapInstance,omitempty"`
	OnapName        *string                 `json:"onapName,omitempty"`
	PolicyFilter    *[]string               `json:"policyFilter,omitempty"`
	PolicyName      *string                 `json:"policyName,omitempty"`

	// TimeOffset Time offset in hours and minutes, e.g., '+02:00' or '-05:00'
	TimeOffset *string `json:"timeOffset,omitempty"`

	// TimeZone Timezone in IANA format (e.g., 'America/NewYork', 'Europe/Paris', 'UTC')
	TimeZone *string `json:"timeZone,omitempty"`
}

// OPADecisionResponse defines model for OPADecisionResponse.
type OPADecisionResponse struct {
	Output     *map[string]interface{} `json:"output,omitempty"`
	PolicyName *string                 `json:"policyName,omitempty"`
}

// StatisticsReport defines model for StatisticsReport.
type StatisticsReport struct {
	Code                        *int32 `json:"code,omitempty"`
	DecisionFailureCount        *int64 `json:"decisionFailureCount,omitempty"`
	DecisionSuccessCount        *int64 `json:"decisionSuccessCount,omitempty"`
	DeployFailureCount          *int64 `json:"deployFailureCount,omitempty"`
	DeploySuccessCount          *int64 `json:"deploySuccessCount,omitempty"`
	IndeterminantDecisionsCount *int64 `json:"indeterminantDecisionsCount,omitempty"`
	TotalErrorCount             *int64 `json:"totalErrorCount,omitempty"`
	TotalPoliciesCount          *int64 `json:"totalPoliciesCount,omitempty"`
	TotalPolicyTypesCount       *int64 `json:"totalPolicyTypesCount,omitempty"`
	UndeployFailureCount        *int64 `json:"undeployFailureCount,omitempty"`
	UndeploySuccessCount        *int64 `json:"undeploySuccessCount,omitempty"`
}

// DecisionParams defines parameters for Decision.
type DecisionParams struct {
	// XONAPRequestID RequestID for http transaction
	XONAPRequestID *openapi_types.UUID `json:"X-ONAP-RequestID,omitempty"`
}

// HealthcheckParams defines parameters for Healthcheck.
type HealthcheckParams struct {
	// XONAPRequestID RequestID for http transaction
	XONAPRequestID *openapi_types.UUID `json:"X-ONAP-RequestID,omitempty"`
}

// StatisticsParams defines parameters for Statistics.
type StatisticsParams struct {
	// XONAPRequestID RequestID for http transaction
	XONAPRequestID *openapi_types.UUID `json:"X-ONAP-RequestID,omitempty"`
}

// DecisionJSONRequestBody defines body for Decision for application/json ContentType.
type DecisionJSONRequestBody = OPADecisionRequest
