[tox]
env_list = py311, mypy, bandit, pylama, pyroma, pydocstyle

[testenv]
deps = pytest
commands = poetry install -v {envbindir}/pytest tests/

[testenv:coverage]
deps = pytest-cov
       onapsdk==14.2.0+tnap
       kafka-python>=2.0.2
       grpcio==1.68.1
       grpcio-tools==1.68.1

       
skip_install = True
setenv =
    PYTHONPATH = app
commands = pytest tests/ --cov=src/taasossdk --cov-report term-missing --cov-report xml

[testenv:mypy]
skip_install = True
deps =
    mypy
    types-requests
    types-PyYAML
commands = mypy --strict app/

[testenv:bandit]
skip_install = True
deps = bandit
commands = bandit app/ -r

[testenv:pylama]
description = Run code linting with pylama
basepython = python3.11
skip_install = True
deps =
    pylama
    setuptools<81
commands =
    pylama app/

[testenv:pyroma]
deps = pyroma
skip_install = True
commands = pyroma .

[testenv:pydocstyle]
deps = pydocstyle
skip_install = True
commands = pydocstyle app/
